name: Release
run-name: ${{ github.workflow }} ${{ github.event.inputs.release-version }}
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Enter version to release (e.g., 1.0.1).
        required: false
jobs:
  perform:
    if: github.event_name == 'workflow_dispatch' && github.repository_owner == 'spring-io'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Set up release environment
      run: |
        echo RELEASE_VERSION=${{ github.event.inputs.release-version }} >> $GITHUB_ENV
        echo RELEASE_NPM_TOKEN=${{ secrets.NPM_TOKEN }} >> $GITHUB_ENV
    - name: Build, tag, and publish npm package
      run: ./npm/release.sh
